const DEFAULT_NAMES = [
  "Kamal Salik",
  "Abdul Rahiman BPT",
  "Abubakkar Abu Mansoor 1",
  "Mohammed Sharif",
  "Jaibunnisa Salik",
  "Asif Ibrahim",
  "Mansoor Abdullah 1",
  "Abubakkar Abu Mansoor 2",
  "Mohammad Ali BPT",
  "Rahamathulla Dubai",
  "Thoufique Salik",
  "Sirajutheen",
  "Sabina Abdurrahmaan",
  "Khalid Salik",
  "Riyaz Salik",
  "Khalil Salik",
  "Rubina",
  "Kalam Salik",
  "Jamil Ahmed",
  "Shajida Rajmuhammad",
  "Abdussalaam Bhndp",
  "Abubakkar Abu Mansoor 3",
  "Parveen Iqbal",
  "Samsudeen",
  "Badrun Zakir",
  "Rashid Sahib",
  "Abdurrahmaan Bhndp",
  "Rahamathulla Dubai",
  "Khalil Salik 2",
  "Noman Adab Khan",
  "Shameem Salam",
  "Rubina",
  "Kadar Salik",
  "Afzal Safiya",
  "Kalam Salik 2",
  "Sultan",
  "Shahul Kadarbasha",
  "Arshad Zarina",
  "Abida Basha",
  "Kamal Salik 2"
];
const STORAGE="family_bc_two_winners_wheel_v5";
const $=id=>document.getElementById(id);
const canvas=$("wheel"), ctx=canvas.getContext("2d");
let state={units:[], wheelOrder:[], winners:[], audit:[], settings:{memberCount:40, monthCount:20, drawPerMonth:2, startMonth:"2026-07", runnerNames:[]}};
let spinning=false, angle=0, velocity=0, raf=null, tickerTimer=null, autoStopTimer=null, selected=null, selectedIndex=-1, displayUnits=null, displayHighlight=-1, lastPegIndex=-1, lastTickAt=0, spinLastTime=0;
let audioCtx=null, tickOsc=null, tickGain=null, tickTimer=null;

function months(){const out=[], s=settings(), [year,month]=s.startMonth.split("-").map(Number), start=new Date(year,month-1,1), total=s.monthCount;for(let i=0;i<total;i++){const d=new Date(start.getFullYear(),start.getMonth()+i,1);out.push(d.toLocaleString("en-US",{month:"long",year:"numeric"}));}return out;}
function todayLabel(){const d=new Date();return `${d.getDate()}-${d.toLocaleString("en-GB",{month:"long"})}-${d.getFullYear()}`;}
function settings(){return {memberCount:Math.max(1,Number(state.settings?.memberCount)||40),monthCount:Math.max(1,Number(state.settings?.monthCount)||20),drawPerMonth:Math.max(1,Number(state.settings?.drawPerMonth)||2),startMonth:/^\d{4}-\d{2}$/.test(state.settings?.startMonth||"")?state.settings.startMonth:"2026-07",runnerNames:Array.isArray(state.settings?.runnerNames)?state.settings.runnerNames:[]};}
function schedule(){return Array.from({length:settings().monthCount},()=>settings().drawPerMonth);}
function maxWinnersPerMonth(){return Math.max(1,...schedule());}
function drawComplete(){return state.winners.length>=state.units.length;}
function finalMonthCount(){const plan=schedule();return Math.max(1,plan[plan.length-1]||settings().drawPerMonth);}
function finalAutoReady(){return state.units.length>0&&!drawComplete()&&state.winners.length>=Math.max(0,state.units.length-finalMonthCount());}
function normalizeState(){state.settings=state.settings||{};state.settings.memberCount=Math.max(1,Number(state.settings.memberCount)||state.units?.length||40);state.settings.monthCount=Math.max(1,Number(state.settings.monthCount)||20);state.settings.drawPerMonth=Math.max(1,Number(state.settings.drawPerMonth)||2);state.settings.startMonth=/^\d{4}-\d{2}$/.test(state.settings.startMonth||"")?state.settings.startMonth:"2026-07";state.settings.runnerNames=Array.isArray(state.settings.runnerNames)?state.settings.runnerNames:[];state.units=Array.isArray(state.units)?state.units:[];state.winners=Array.isArray(state.winners)?state.winners:[];state.wheelOrder=Array.isArray(state.wheelOrder)?state.wheelOrder:[];state.audit=Array.isArray(state.audit)?state.audit:[];}
function initAudio(){if(!audioCtx) audioCtx=new (window.AudioContext||window.webkitAudioContext)();}
function beep(freq=600,dur=.06,type="square",vol=.05){if(!audioCtx)return; const o=audioCtx.createOscillator(), g=audioCtx.createGain(); o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur);}
function startSpinSound(){initAudio(); beep(330,.12,"sawtooth",.08); setTimeout(()=>beep(520,.12,"sawtooth",.08),100);}
function slowTickSound(){clearInterval(tickTimer);}
function fanfare(){initAudio(); clearInterval(tickTimer); [523,659,784,1046].forEach((f,i)=>setTimeout(()=>beep(f,.18,"triangle",.09),i*130));}
function rand(max){max=Math.floor(Number(max));if(!Number.isFinite(max)||max<1)throw new Error("Invalid random range");const limit=0x100000000-(0x100000000%max), a=new Uint32Array(1);do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%max;}
function secureShuffle(arr){let a=[...arr];for(let i=a.length-1;i>0;i--){let j=rand(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function audit(action, detail={}){state.audit.push({no:state.audit.length+1,action,time:new Date().toISOString(),detail});}
function appendCell(row,text,tag="td",className=""){const cell=document.createElement(tag);if(className)cell.className=className;cell.textContent=text;row.appendChild(cell);return cell;}
function appendBoldCell(row,text,tag="td",className=""){const cell=document.createElement(tag);if(className)cell.className=className;const b=document.createElement("b");b.textContent=text;cell.appendChild(b);row.appendChild(cell);return cell;}
function renderHeader(head,maxW){head.textContent="";const row=document.createElement("tr");appendCell(row,"#","th","sr");appendCell(row,"Month","th");for(let i=0;i<maxW;i++)appendCell(row,"Member "+(i+1),"th");head.appendChild(row);}
function renderRows(tbody,rows,maxW){tbody.textContent="";rows.forEach((r,i)=>{const row=document.createElement("tr");appendBoldCell(row,String(i+1),"td","sr");appendBoldCell(row,r.month);for(let j=0;j<maxW;j++)appendCell(row,r.names[j]||"---");tbody.appendChild(row);});if(!rows.length){const row=document.createElement("tr"), cell=appendCell(row,"No draw yet.");cell.colSpan=maxW+2;tbody.appendChild(row);}}
function renderResultsTable(container,rows,maxW){container.textContent="";const table=document.createElement("table"), thead=document.createElement("thead"), tbody=document.createElement("tbody");renderHeader(thead,maxW);renderRows(tbody,rows,maxW);table.append(thead,tbody);container.appendChild(table);}
function csvCell(value){let s=String(value??"");if(/^[=+\-@]/.test(s))s="'"+s;return `"${s.replace(/"/g,'""')}"`;}
function notify(message,title="Message"){showDialog({message,title,okText:"OK"});}
function ask(message,onYes,onNo,title="Confirm"){showDialog({message,title,okText:"OK",cancelText:"Cancel",onYes,onNo});}
function showDialog({message,title="Message",okText="OK",cancelText="",onYes,onNo}){const overlay=$("dialogOverlay"), cancel=$("dialogCancel"), ok=$("dialogOk");$("dialogTitle").textContent=title;$("dialogMessage").textContent=message;ok.textContent=okText;cancel.textContent=cancelText||"Cancel";cancel.style.display=cancelText?"inline-flex":"none";overlay.classList.add("show");ok.focus();function close(result){overlay.classList.remove("show");ok.onclick=null;cancel.onclick=null;if(result&&onYes)onYes();if(!result&&onNo)onNo();}ok.onclick=()=>close(true);cancel.onclick=()=>close(false);}
function loadState(){document.title=$("pageTitle").textContent="Family BC 2026 Draw "+todayLabel(); const saved=localStorage.getItem(STORAGE)||localStorage.getItem("family_bc_40_names_wheel_v3"); if(saved){try{state=JSON.parse(saved)}catch{}} normalizeState(); if(!state.units.length){state.units=DEFAULT_NAMES; state.settings.memberCount=DEFAULT_NAMES.length; state.settings.monthCount=20; state.settings.drawPerMonth=2; state.settings.startMonth="2026-07"; state.settings.runnerNames=[]; state.wheelOrder=secureShuffle(DEFAULT_NAMES.map((name,i)=>({id:i,name}))); state.winners=[]; state.audit=[]; audit("initial-default-load",{members:state.units.length}); save();} $("startMonth").value=settings().startMonth;$("memberCount").value=settings().memberCount;$("monthCount").value=settings().monthCount;$("drawPerMonth").value=settings().drawPerMonth;$("names").value=state.units.join("\n");updateRunnerChoices(settings().runnerNames); render();requestAnimationFrame(()=>drawWheel(displayHighlight));}
function setSetupHidden(hidden){document.querySelector(".app").classList.toggle("setupHidden",hidden);$("setupToggle").textContent="Hide Setup ◀";$("setupToggle").title="Hide draw setup";$("setupToggle").setAttribute("aria-expanded",String(!hidden));$("setupShow").setAttribute("aria-expanded",String(!hidden));localStorage.setItem(STORAGE+"_setup_hidden",hidden?"1":"0");requestAnimationFrame(()=>drawWheel(displayHighlight));setTimeout(()=>drawWheel(displayHighlight),430);}
function setSetupLocked(locked){document.querySelector(".app").classList.toggle("setupLocked",locked);["startMonth","memberCount","monthCount","drawPerMonth","names","load"].forEach(id=>$(id).disabled=locked);document.querySelectorAll("#drawRunners input").forEach(x=>x.disabled=locked);$("lockSetup").textContent=locked?"Unlock Setup":"Lock Setup";localStorage.setItem(STORAGE+"_setup_locked",locked?"1":"0");}
function parse(){return $("names").value.split(/\n/).map(x=>x.trim()).filter(Boolean);}
function parseRunners(){return Array.from(document.querySelectorAll("#drawRunners input:checked")).map(x=>x.value).filter(Boolean);}
function drawRunnerLimit(){return Math.max(1,Number($("drawPerMonth").value)||settings().drawPerMonth);}
function enforceRunnerLimit(changed){const limit=drawRunnerLimit(), checked=Array.from(document.querySelectorAll("#drawRunners input:checked"));if(checked.length>limit){if(changed)changed.checked=false;else checked.slice(limit).forEach(x=>x.checked=false);notify("You can select only "+limit+" draw runner(s) because Draw / Month is "+limit+".","Selection Limit");}}
function updateRunnerChoices(selectedNames=parseRunners()){const box=$("drawRunners"), units=parse(), selected=[...selectedNames], counts=new Map(), locked=document.querySelector(".app").classList.contains("setupLocked");box.innerHTML="";units.forEach((name,i)=>{const key=name.toLowerCase(), count=(counts.get(key)||0)+1;counts.set(key,count);const row=document.createElement("label"), check=document.createElement("input"), text=document.createElement("span");row.className="runnerOption";check.type="checkbox";check.value=name;check.disabled=locked;check.addEventListener("change",()=>enforceRunnerLimit(check));const matchIndex=selected.findIndex(x=>x.toLowerCase()===key);if(matchIndex>=0){check.checked=true;selected.splice(matchIndex,1);}text.textContent=count>1?`${name} (${count})`:name;row.append(check,text);box.appendChild(row);});enforceRunnerLimit();}
function runnerRecords(units, runnerNames){const used=new Set(), byName=new Map();units.forEach((name,id)=>{const key=name.toLowerCase();if(!byName.has(key))byName.set(key,[]);byName.get(key).push({id,name});});return runnerNames.map((name,i)=>{const list=byName.get(name.toLowerCase())||[], match=list.find(x=>!used.has(x.id));if(!match)return null;used.add(match.id);return {id:match.id,name:match.name,month:months()[0],monthIndex:0,winnerNo:i+1,time:"Assigned as draw runner"};});}
function drawnIds(){return new Set(state.winners.map(w=>w.id));}
function remainingWheel(){const d=drawnIds();return state.wheelOrder.filter(x=>!d.has(x.id));}
function assignFinalMonthIfReady(){if(!finalAutoReady())return false;const ms=months(), lastIndex=settings().monthCount-1, rem=remainingWheel(), existing=state.winners.filter(w=>w.monthIndex===lastIndex).length;rem.forEach((unit,i)=>{const rec={id:unit.id,name:unit.name,month:ms[lastIndex],monthIndex:lastIndex,winnerNo:existing+i+1,time:"Assigned automatically as final month remaining member"};state.winners.push(rec);audit("auto-final-month-assigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo});});return rem.length>0;}
function wheelDisplay(){const units=displayUnits||remainingWheel();if(units.length)return units;if(state.wheelOrder?.length)return state.wheelOrder;if(state.units?.length)return state.units.map((name,i)=>({id:i,name}));return [];}
function pointerIndex(units){const n=Math.max(units.length,1), slice=Math.PI*2/n;return Math.floor((((0-angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2))/slice);}
function pegTick(speed=1){const pointer=$("wheelPointer"); pointer.classList.remove("tick"); void pointer.offsetWidth; pointer.classList.add("tick"); beep(620+Math.min(520,speed*115),Math.max(.012,.03-Math.min(.018,speed*.004)),"square",.034);}
function syncPegTick(){const units=wheelDisplay(); if(units.length<2)return; const idx=pointerIndex(units), now=performance.now(); if(lastPegIndex<0){lastPegIndex=idx;return} if(idx!==lastPegIndex){const diff=Math.abs(idx-lastPegIndex), step=Math.min(diff,units.length-diff);lastPegIndex=idx;lastTickAt=now;pegTick(step);}}
function monthIndex(){let drawn=state.winners.length;const plan=schedule();for(let i=0;i<plan.length;i++){if(drawn<plan[i])return i;drawn-=plan[i];}return plan.length-1;}
function winnerNum(){const mi=monthIndex();return state.winners.filter(w=>w.monthIndex===mi).length+1;}
function color(i){return ["#0b5ed7","#10a05f","#ffcc33","#df2b2b","#7c3aed","#0891b2","#f97316","#16a34a","#e11d48","#2563eb"][i%10];}
function short(n){return n.length>24?n.slice(0,22)+"...":n;}
function drawWheel(highlight=-1){if(!Number.isFinite(angle))angle=0;const units=wheelDisplay(); const n=Math.max(units.length,1); const w=canvas.width,cx=w/2,cy=w/2,r=w/2-18,slice=Math.PI*2/n; ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,w,w); ctx.save(); ctx.translate(cx,cy); ctx.rotate(angle); for(let i=0;i<n;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,i*slice,(i+1)*slice);ctx.closePath();ctx.fillStyle=color(i);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.8)";ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate(i*slice+slice/2);ctx.textAlign="right";ctx.fillStyle="#fff";ctx.font=n>60?"900 19px Calibri":n>30?"900 23px Calibri":"900 28px Calibri";ctx.shadowColor="#000";ctx.shadowBlur=5;ctx.fillText(short(units[i]?.name||""),r-22,8);ctx.restore();} ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.lineWidth=12;ctx.strokeStyle="#fff";ctx.stroke();for(let i=0;i<n;i++){const a=i*slice,x=Math.cos(a)*(r-2),y=Math.sin(a)*(r-2);ctx.beginPath();ctx.arc(x,y,n>60?5:7,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#050505";ctx.stroke();}ctx.restore();}
function spinLoop(now=performance.now()){if(!spinLastTime)spinLastTime=now;const dt=Math.min(40,now-spinLastTime)/16.67;spinLastTime=now;angle+=velocity*dt;drawWheel();syncPegTick();raf=requestAnimationFrame(spinLoop);}
function start(){initAudio(); if(state.units.length!==settings().memberCount){notify("Please load exactly "+settings().memberCount+" names first.","Names Required");return} if(finalAutoReady()){assignFinalMonthIfReady();save();render();showSummary();return} if(spinning||remainingWheel().length===0)return; spinning=true; selected=null; selectedIndex=-1; displayUnits=null; displayHighlight=-1; lastPegIndex=-1; lastTickAt=0; spinLastTime=0; velocity=.92+Math.random()*.18; $("status").textContent="SPINNING"; $("start").disabled=true;$("latest").textContent="---";$("ticker").textContent="SPINNING..."; startSpinSound(); tickerTimer=setInterval(()=>{$("ticker").textContent=["SPINNING FAST...","GOOD LUCK...","DRAW IN PROGRESS..."][rand(3)];},260); spinLoop(); autoStopTimer=setTimeout(stop,1600);}
function stop(){if(!spinning)return; clearInterval(tickerTimer); slowTickSound(); $("ticker").textContent="SLOWING DOWN..."; const rem=remainingWheel(); selectedIndex=rand(rem.length); selected=rem[selectedIndex]; displayUnits=rem; displayHighlight=selectedIndex; cancelAnimationFrame(raf); const full=Math.PI*2, slice=full/rem.length, pointer=0, selectedCenter=selectedIndex*slice+slice/2; const targetBase=pointer-selectedCenter, current=angle, currentMod=((current%full)+full)%full, targetMod=((targetBase%full)+full)%full; const extraTurns=19+rand(5), delta=((targetMod-currentMod+full)%full)+(full*extraTurns), final=current+delta; const startTime=performance.now(), duration=6500+rand(900); lastPegIndex=pointerIndex(rem); let lastAngle=current; function ease(t){return 1-Math.pow(1-t,4)} function slow(now){const t=Math.min(1,(now-startTime)/duration); angle=current+delta*ease(t); const speed=Math.abs(angle-lastAngle); lastAngle=angle; drawWheel(selectedIndex); syncPegTick(); if(speed>.24)$("ticker").textContent="SLOWING DOWN..."; if(t>.48&&t<.78)$("ticker").textContent="ALMOST THERE..."; if(t>=.78&&t<1)$("ticker").textContent="FINAL MOMENTS..."; if(t<1)requestAnimationFrame(slow);else finish();} requestAnimationFrame(slow);}
function finish(){spinning=false; const m=months()[monthIndex()], wn=winnerNum(); const rec={id:selected.id,name:selected.name,month:m,monthIndex:monthIndex(),winnerNo:wn,time:new Date().toLocaleString()}; state.winners.push(rec);audit("winner-drawn",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo,remainingAfterDraw:remainingWheel().length}); const finalAssigned=assignFinalMonthIfReady(); save(); $("ticker").textContent=finalAssigned?"Final month assigned automatically":selected.name; $("latest").textContent=selected.name; $("status").textContent="WINNER REVEALED"; fanfare(); showPopup(rec); render();}
function next(){displayUnits=null;displayHighlight=-1;$("ticker").textContent="Click BISMILLAAH to spin the wheel";$("latest").textContent="---";$("start").disabled=drawComplete();$("status").textContent=drawComplete()?"COMPLETE":"READY";drawWheel();}
function showPopup(rec){$("popMonth").textContent=rec.month+" Member #"+rec.winnerNo;$("popName").textContent=rec.name;$("overlay").classList.add("show");confetti();}
function confetti(){const box=$("confetti");box.innerHTML="";for(let i=0;i<160;i++){const p=document.createElement("i");p.style.left=Math.random()*100+"vw";p.style.background=color(i);p.style.animationDelay=Math.random()*0.4+"s";p.style.animationDuration=2+Math.random()*2+"s";box.appendChild(p);setTimeout(()=>p.remove(),4500);}}
function render(){const rem=remainingWheel(), ms=months(), plan=schedule(), mi=drawComplete()?plan.length-1:monthIndex(), wn=winnerNum(), maxW=maxWinnersPerMonth(); $("wheelPanel").classList.toggle("drawComplete",drawComplete());$("total").textContent=state.units.length;$("remaining").textContent=rem.length;$("drawn").textContent=state.winners.length;$("month").textContent=drawComplete()?"Completed":finalAutoReady()?ms[plan.length-1]:ms[mi];$("winnerNo").textContent=drawComplete()?"All members drawn":finalAutoReady()?"Final month will be assigned automatically":"Current Draw: "+ms[mi]+" - Member "+wn+" of "+plan[mi];$("round").textContent=drawComplete()?"Complete":finalAutoReady()?"Final month auto assignment":"Month "+(mi+1)+" / "+settings().monthCount;$("start").disabled=drawComplete()||spinning||finalAutoReady();$("undo").disabled=spinning||state.winners.length===0;$("summary").disabled=!drawComplete();$("shareAll").disabled=!drawComplete();drawWheel(displayHighlight);renderHeader($("historyHead"),maxW);renderRows($("history"),summaryRows(),maxW);}
function exportCSV(){const rows=summaryRows(), maxW=maxWinnersPerMonth(), lines=[];lines.push(["#","Month",...Array.from({length:maxW},(_,i)=>"Member "+(i+1))].map(csvCell).join(","));rows.forEach((r,i)=>lines.push([i+1,r.month,...r.names].map(csvCell).join(",")));lines.push("");lines.push(["Audit #","Action","Time","Detail"].map(csvCell).join(","));state.audit.forEach(a=>lines.push([a.no,a.action,a.time,JSON.stringify(a.detail||{})].map(csvCell).join(","))); const blob=new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="family-bc-wheel-draw-results.csv";a.click();URL.revokeObjectURL(url);}
function backupState(){audit("backup-created",{winners:state.winners.length,members:state.units.length});save();const blob=new Blob([JSON.stringify({version:6,savedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="family-bc-draw-backup.json";a.click();URL.revokeObjectURL(url);}
function restoreState(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result), restored=data.state||data; if(!Array.isArray(restored.units)||!Array.isArray(restored.wheelOrder)||!Array.isArray(restored.winners))throw new Error("Invalid backup"); state=restored;normalizeState();audit("backup-restored",{fileName:file.name||"backup",winners:state.winners.length,members:state.units.length});save();displayUnits=null;displayHighlight=-1;$("startMonth").value=settings().startMonth;$("memberCount").value=settings().memberCount;$("monthCount").value=settings().monthCount;$("drawPerMonth").value=settings().drawPerMonth;$("names").value=state.units.join("\n");updateRunnerChoices(settings().runnerNames);render();notify("Backup restored successfully.","Backup Restored");}catch(e){notify("Could not restore this backup file.","Restore Failed");}};reader.readAsText(file);}
function summaryRows(){const ms=months(), maxW=maxWinnersPerMonth();return ms.map((m,i)=>{const monthWinners=state.winners.filter(x=>x.monthIndex===i);return {month:m,names:Array.from({length:maxW},(_,j)=>monthWinners.find(x=>x.winnerNo===j+1)?.name||"")};});}
function showSummary(){const rows=summaryRows(), maxW=maxWinnersPerMonth();$("summaryIntro").textContent=drawComplete()?"All draws are complete.":"Draw is not complete yet.";renderResultsTable($("summaryList"),rows,maxW);$("summaryOverlay").classList.add("show");}
function shareAllResults(){if(!drawComplete()){notify("Share All is available after the full draw is complete.","Draw Not Complete");return} const rows=summaryRows();let msg=document.title+"\n\nFinal Draw Results\n";rows.forEach((r,i)=>{msg+=`${i+1}. ${r.month}: ${r.names.filter(Boolean).join(", ")}\n`;});window.open("https://wa.me/?text="+encodeURIComponent(msg),"_blank");}
function undoLast(){if(spinning||!state.winners.length)return;const autoText="Assigned automatically as final month remaining member";let autoCount=0;while(state.winners.length&&state.winners[state.winners.length-1].time===autoText){state.winners.pop();autoCount++;}const last=state.winners[state.winners.length-1];if(!last){save();render();return}const extra=autoCount?"\n\nThis will also remove "+autoCount+" automatic final month member(s).":"";ask("Undo last member: "+last.name+"?"+extra,()=>{const undone=state.winners.pop();audit("winner-undone",{id:undone.id,name:undone.name,month:undone.month,winnerNo:undone.winnerNo,autoFinalRemoved:autoCount});displayUnits=null;displayHighlight=-1;save();$("latest").textContent="---";$("ticker").textContent="Click BISMILLAAH to spin the wheel";$("status").textContent="READY";render();},()=>{assignFinalMonthIfReady();save();render();},"Undo Last Draw");}
function setPresentation(on){document.querySelector(".app").classList.toggle("presentation",on);if(on)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.().catch(()=>{});}
$("load").onclick=()=>{const units=parse(), runnerNames=parseRunners(), startMonth=$("startMonth").value||"2026-07", memberCount=Math.max(1,Number($("memberCount").value)||0), monthCount=Math.max(1,Number($("monthCount").value)||0), drawPerMonth=Math.max(1,Number($("drawPerMonth").value)||0), expected=monthCount*drawPerMonth; if(memberCount!==expected){notify("Total Members must be Total Months x Total Draw Per Month.\n\n"+monthCount+" months x "+drawPerMonth+" draw per month needs "+expected+" members.","Setup Mismatch");return} if(units.length!==memberCount){notify("You entered "+units.length+" names.\n\nPlease enter exactly "+memberCount+" names, or update Total Members.","Member Count Mismatch");return} if(runnerNames.length>drawPerMonth){notify("Draw Runners cannot be more than Draw / Month.\n\nPlease enter up to "+drawPerMonth+" runner name(s).","Too Many Draw Runners");return} const previousSettings=state.settings; state.settings={memberCount,monthCount,drawPerMonth,startMonth,runnerNames}; const assigned=runnerRecords(units,runnerNames); const missing=runnerNames.filter((_,i)=>!assigned[i]); if(missing.length){state.settings=previousSettings;notify("Draw Runner name(s) not found in member list:\n\n"+missing.join(", "),"Draw Runner Not Found");return} displayUnits=null;displayHighlight=-1;state.units=units; state.wheelOrder=secureShuffle(units.map((name,i)=>({id:i,name}))); state.winners=assigned.filter(Boolean); state.audit=[]; audit("setup-loaded",{members:memberCount,months:monthCount,drawPerMonth,startMonth,drawRunners:runnerNames.length}); state.winners.forEach(rec=>audit("runner-preassigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo})); assignFinalMonthIfReady(); save(); render(); notify(memberCount+" names loaded from "+months()[0]+" across "+monthCount+" months.\n\n"+state.winners.length+" member(s) assigned automatically for fixed first/last month rules.","Names Loaded");};
$("reset").onclick=()=>{ask("Reset all draw results?\n\nDraw runners and final month rules will stay assigned automatically.",()=>{displayUnits=null;displayHighlight=-1;state.audit=[];audit("draw-reset",{members:state.units.length});state.winners=runnerRecords(state.units,settings().runnerNames).filter(Boolean);state.winners.forEach(rec=>audit("runner-preassigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo}));assignFinalMonthIfReady();save();next();render();},null,"Reset Draw");};
$("start").onclick=start;$("setupToggle").onclick=()=>setSetupHidden(true);$("setupShow").onclick=()=>setSetupHidden(false);$("lockSetup").onclick=()=>setSetupLocked(!document.querySelector(".app").classList.contains("setupLocked"));$("continue").onclick=()=>{$("overlay").classList.remove("show");if(drawComplete())showSummary();};$("export").onclick=exportCSV;$("print").onclick=()=>window.print();
$("undo").onclick=undoLast;$("backup").onclick=backupState;$("restore").onclick=()=>$("restoreFile").click();$("restoreFile").onchange=e=>{if(e.target.files[0])restoreState(e.target.files[0]);e.target.value="";};$("presentation").onclick=()=>setPresentation(true);$("exitPresentation").onclick=()=>setPresentation(false);$("summary").onclick=showSummary;$("summaryClose").onclick=()=>$("summaryOverlay").classList.remove("show");$("shareAll").onclick=shareAllResults;$("summaryShare").onclick=shareAllResults;
$("names").addEventListener("input",()=>updateRunnerChoices());
$("drawPerMonth").addEventListener("input",()=>enforceRunnerLimit());
loadState();setSetupHidden(localStorage.getItem(STORAGE+"_setup_hidden")==="1");setSetupLocked(localStorage.getItem(STORAGE+"_setup_locked")==="1");setTimeout(()=>drawWheel(displayHighlight),650);
