const DEFAULT_NAMES = [];
const STORAGE="family_bc_two_winners_wheel_v5";
const APP_TITLE="Seettu Kulukkal App";
const WINNER_REVEAL_DELAY_MS=1000;
const $=id=>document.getElementById(id);
const canvas=$("wheel"), ctx=canvas.getContext("2d");
let state={units:[], wheelOrder:[], winners:[], audit:[], settings:{memberCount:40, monthCount:20, drawPerMonth:2, startMonth:"2026-07", runnerNames:[], drawMode:"full", targetDrawCount:2}};
let spinning=false, angle=0, velocity=0, raf=null, tickerTimer=null, autoStopTimer=null, revealTimer=null, selected=null, selectedIndex=-1, displayUnits=null, displayHighlight=-1, lastPegIndex=-1, lastTickAt=0, spinLastTime=0;
let audioCtx=null, tickOsc=null, tickGain=null, tickTimer=null;
let pendingSetupMode=null;
let autoOpenSetupWizard=false;

function monthLabel(date){return `${date.toLocaleString("en-US",{month:"long"})}-${date.getFullYear()}`;}
function monthValueLabel(value){const [year,month]=String(value||"").split("-").map(Number);return Number.isFinite(year)&&Number.isFinite(month)?monthLabel(new Date(year,month-1,1)):String(value||"");}
function months(){const out=[], s=settings(), [year,month]=s.startMonth.split("-").map(Number), start=new Date(year,month-1,1), total=s.monthCount;for(let i=0;i<total;i++){const d=new Date(start.getFullYear(),start.getMonth()+i,1);out.push(monthLabel(d));}return out;}
function todayLabel(){const d=new Date();return `${d.getDate()}-${d.toLocaleString("en-GB",{month:"long"})}-${d.getFullYear()}`;}
function settings(){const drawMode=state.settings?.drawMode==="specific"?"specific":"full", drawPerMonth=Math.max(1,Number(state.settings?.drawPerMonth)||2), targetDrawCount=Math.max(1,Number(state.settings?.targetDrawCount)||drawPerMonth);return {memberCount:Math.max(1,Number(state.settings?.memberCount)||40),monthCount:Math.max(1,Number(state.settings?.monthCount)||20),drawPerMonth,startMonth:/^\d{4}-\d{2}$/.test(state.settings?.startMonth||"")?state.settings.startMonth:"2026-07",runnerNames:Array.isArray(state.settings?.runnerNames)?state.settings.runnerNames:[],drawMode,targetDrawCount};}
function schedule(){const s=settings();return s.drawMode==="specific"?[s.targetDrawCount]:Array.from({length:s.monthCount},()=>s.drawPerMonth);}
function targetWinnerCount(){return schedule().reduce((sum,n)=>sum+n,0);}
function maxWinnersPerMonth(){return Math.max(1,...schedule());}
function drawComplete(){return state.winners.length>=targetWinnerCount();}
function finalMonthCount(){const plan=schedule();return Math.max(1,plan[plan.length-1]||settings().drawPerMonth);}
function finalAutoReady(){return settings().drawMode==="full"&&state.units.length>0&&!drawComplete()&&state.winners.length>=Math.max(0,state.units.length-finalMonthCount());}
function normalizeState(){state.settings=state.settings||{};state.settings.memberCount=Math.max(1,Number(state.settings.memberCount)||state.units?.length||40);state.settings.monthCount=Math.max(1,Number(state.settings.monthCount)||20);state.settings.drawPerMonth=Math.max(1,Number(state.settings.drawPerMonth)||2);state.settings.startMonth=/^\d{4}-\d{2}$/.test(state.settings.startMonth||"")?state.settings.startMonth:"2026-07";state.settings.runnerNames=Array.isArray(state.settings.runnerNames)?state.settings.runnerNames:[];state.settings.drawMode=state.settings.drawMode==="specific"?"specific":"full";state.settings.targetDrawCount=Math.max(1,Number(state.settings.targetDrawCount)||Number(state.settings.drawPerMonth)||2);state.units=Array.isArray(state.units)?state.units:[];state.winners=Array.isArray(state.winners)?state.winners:[];state.wheelOrder=Array.isArray(state.wheelOrder)?state.wheelOrder:[];state.audit=Array.isArray(state.audit)?state.audit:[];}
function isUntouchedDefaultSetup(){return state.winners.length===0&&state.audit.some(entry=>entry?.action==="initial-default-load");}
function blankSetup(){state={units:[],wheelOrder:[],winners:[],audit:[],settings:{memberCount:40,monthCount:20,drawPerMonth:2,startMonth:"2026-07",runnerNames:[],drawMode:"full",targetDrawCount:2}};}
function initAudio(){if(!audioCtx) audioCtx=new (window.AudioContext||window.webkitAudioContext)();}
function beep(freq=600,dur=.06,type="square",vol=.05){if(!audioCtx)return; const o=audioCtx.createOscillator(), g=audioCtx.createGain(); o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur);}
function tone(freq,start,dur,type="triangle",vol=.14){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime+start);g.gain.setValueAtTime(.0001,audioCtx.currentTime+start);g.gain.exponentialRampToValueAtTime(vol,audioCtx.currentTime+start+.025);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+start+dur);o.connect(g);g.connect(audioCtx.destination);o.start(audioCtx.currentTime+start);o.stop(audioCtx.currentTime+start+dur+.05);}
function noiseHit(start,dur=.22,vol=.16){if(!audioCtx)return;const len=Math.floor(audioCtx.sampleRate*dur),buf=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),g=audioCtx.createGain();filter.type="highpass";filter.frequency.value=1800;g.gain.setValueAtTime(vol,audioCtx.currentTime+start);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+start+dur);src.buffer=buf;src.connect(filter);filter.connect(g);g.connect(audioCtx.destination);src.start(audioCtx.currentTime+start);}
function startSpinSound(){initAudio(); beep(330,.12,"sawtooth",.08); setTimeout(()=>beep(520,.12,"sawtooth",.08),100);}
function slowTickSound(){clearInterval(tickTimer);}
function fanfare(){initAudio(); clearInterval(tickTimer); if(audioCtx.state==="suspended")audioCtx.resume?.(); const chords=[[523,659,784],[659,784,988],[784,988,1319]], bass=[131,196,262], sparkle=[1046,1319,1568,2093,2637];chords.forEach((ch,i)=>ch.forEach(f=>tone(f,i*.42,.38,"triangle",.18)));bass.forEach((f,i)=>tone(f,i*.42,.32,"sawtooth",.12));sparkle.forEach((f,i)=>tone(f,.16+i*.16,.16,"sine",.11));[0,.18,.36,.78,1.02].forEach(t=>noiseHit(t,.18,.18));tone(1046,1.22,.75,"triangle",.2);tone(1319,1.22,.75,"triangle",.18);tone(1568,1.22,.75,"triangle",.16);}
function rand(max){max=Math.floor(Number(max));if(!Number.isFinite(max)||max<1)throw new Error("Invalid random range");const limit=0x100000000-(0x100000000%max), a=new Uint32Array(1);do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%max;}
function secureShuffle(arr){let a=[...arr];for(let i=a.length-1;i>0;i--){let j=rand(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function audit(action, detail={}){state.audit.push({no:state.audit.length+1,action,time:new Date().toISOString(),detail});}
function appendCell(row,text,tag="td",className=""){const cell=document.createElement(tag);if(className)cell.className=className;cell.textContent=text;row.appendChild(cell);return cell;}
function appendBoldCell(row,text,tag="td",className=""){const cell=document.createElement(tag);if(className)cell.className=className;const b=document.createElement("b");b.textContent=text;cell.appendChild(b);row.appendChild(cell);return cell;}
function renderHeader(head,maxW){head.textContent="";const row=document.createElement("tr");appendCell(row,"#","th","sr");appendCell(row,"Month","th");for(let i=0;i<maxW;i++)appendCell(row,"Member "+(i+1),"th");head.appendChild(row);}
function renderRows(tbody,rows,maxW){tbody.textContent="";rows.forEach((r,i)=>{const row=document.createElement("tr");appendBoldCell(row,String(i+1),"td","sr");appendBoldCell(row,r.month);for(let j=0;j<maxW;j++)appendCell(row,r.names[j]||"---");tbody.appendChild(row);});if(!rows.length){const row=document.createElement("tr"), cell=appendCell(row,"No draw yet.");cell.colSpan=maxW+2;tbody.appendChild(row);}}
function renderResultsTable(container,rows,maxW){container.textContent="";const table=document.createElement("table"), thead=document.createElement("thead"), tbody=document.createElement("tbody");renderHeader(thead,maxW);renderRows(tbody,rows,maxW);table.append(thead,tbody);container.appendChild(table);}
function csvCell(value){let s=String(value??"");if(/^[=+\-@]/.test(s))s="'"+s;return `"${s.replace(/"/g,'""')}"`;}
function notify(message,title="Message"){showDialog({message,title,okText:"OK"});}
function ask(message,onYes,onNo,title="Confirm"){showDialog({message,title,okText:"OK",cancelText:"Cancel",onYes,onNo});}
function showDialog({message,title="Message",okText="OK",cancelText="",onYes,onNo}){const overlay=$("dialogOverlay"), cancel=$("dialogCancel"), ok=$("dialogOk");$("dialogTitle").textContent=title;$("dialogMessage").textContent=message;ok.textContent=okText;cancel.textContent=cancelText||"Cancel";cancel.style.display=cancelText?"inline-flex":"none";overlay.classList.add("show");ok.focus();function close(result){overlay.classList.remove("show");ok.onclick=null;cancel.onclick=null;if(result&&onYes)onYes();if(!result&&onNo)onNo();}ok.onclick=()=>close(true);cancel.onclick=()=>close(false);}
function loadState(){document.title=$("pageTitle").textContent=APP_TITLE; const saved=localStorage.getItem(STORAGE)||localStorage.getItem("family_bc_40_names_wheel_v3"); if(saved){try{state=JSON.parse(saved)}catch{}} normalizeState(); if(!saved||!state.units.length||isUntouchedDefaultSetup()){blankSetup();autoOpenSetupWizard=true;save();} $("startMonth").value=settings().startMonth;$("memberCount").value=settings().memberCount;$("monthCount").value=settings().monthCount;$("drawPerMonth").value=settings().drawPerMonth;$("names").value=state.units.join("\n");updateRunnerChoices(settings().runnerNames); render();requestAnimationFrame(()=>drawWheel(displayHighlight));}
function setSetupHidden(hidden){document.querySelector(".app").classList.toggle("setupHidden",hidden);$("setupToggle").textContent="Hide Setup ◀";$("setupToggle").title="Hide draw setup";$("setupToggle").setAttribute("aria-expanded",String(!hidden));$("setupShow").setAttribute("aria-expanded",String(!hidden));localStorage.setItem(STORAGE+"_setup_hidden",hidden?"1":"0");requestAnimationFrame(()=>drawWheel(displayHighlight));setTimeout(()=>drawWheel(displayHighlight),430);}
function setSetupLocked(locked){document.querySelector(".app").classList.toggle("setupLocked",locked);["startMonth","memberCount","monthCount","drawPerMonth","names","load"].forEach(id=>$(id).disabled=locked);document.querySelectorAll("#drawRunners input").forEach(x=>x.disabled=locked);$("lockSetup").textContent=locked?"Unlock Setup":"Lock Setup";localStorage.setItem(STORAGE+"_setup_locked",locked?"1":"0");}
function parse(){return $("names").value.split(/\n/).map(x=>x.trim()).filter(Boolean);}
function parseRunners(){return Array.from(document.querySelectorAll("#drawRunners input:checked")).map(x=>x.value).filter(Boolean);}
function drawRunnerLimit(){return Math.max(1,Number($("drawPerMonth").value)||settings().drawPerMonth);}
function enforceRunnerLimit(changed){const limit=drawRunnerLimit(), checked=Array.from(document.querySelectorAll("#drawRunners input:checked"));if(checked.length>limit){if(changed)changed.checked=false;else checked.slice(limit).forEach(x=>x.checked=false);notify("You can select only "+limit+" draw runner(s) because Draw / Month is "+limit+".","Selection Limit");}}
function updateRunnerChoices(selectedNames=parseRunners()){const box=$("drawRunners"), units=parse(), selected=[...selectedNames], counts=new Map(), locked=document.querySelector(".app").classList.contains("setupLocked");box.innerHTML="";units.forEach((name,i)=>{const key=name.toLowerCase(), count=(counts.get(key)||0)+1;counts.set(key,count);const row=document.createElement("label"), check=document.createElement("input"), text=document.createElement("span");row.className="runnerOption";check.type="checkbox";check.value=name;check.disabled=locked;check.addEventListener("change",()=>enforceRunnerLimit(check));const matchIndex=selected.findIndex(x=>x.toLowerCase()===key);if(matchIndex>=0){check.checked=true;selected.splice(matchIndex,1);}text.textContent=count>1?`${name} (${count})`:name;row.append(check,text);box.appendChild(row);});enforceRunnerLimit();}
function runnerRecords(units, runnerNames){const used=new Set(), byName=new Map();units.forEach((name,id)=>{const key=name.toLowerCase();if(!byName.has(key))byName.set(key,[]);byName.get(key).push({id,name});});return runnerNames.map((name,i)=>{const list=byName.get(name.toLowerCase())||[], match=list.find(x=>!used.has(x.id));if(!match)return null;used.add(match.id);return {id:match.id,name:match.name,month:months()[0],monthIndex:0,winnerNo:i+1,time:"Assigned as draw runner"};});}
function drawnIds(){return new Set(state.winners.map(w=>w.id));}
function remainingWheel(){const d=drawnIds();return state.wheelOrder.filter(x=>!d.has(x.id));}
function assignFinalMonthIfReady(){if(!finalAutoReady())return false;const ms=months(), lastIndex=settings().monthCount-1, rem=remainingWheel(), existing=state.winners.filter(w=>w.monthIndex===lastIndex).length;rem.forEach((unit,i)=>{const rec={id:unit.id,name:unit.name,month:ms[lastIndex],monthIndex:lastIndex,winnerNo:existing+i+1,time:"Assigned automatically as final month remaining member"};state.winners.push(rec);audit("auto-final-month-assigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo});});return rem.length>0;}
function wheelDisplay(){const units=displayUnits||remainingWheel();if(units.length)return units;if(state.wheelOrder?.length)return state.wheelOrder;if(state.units?.length)return state.units.map((name,i)=>({id:i,name}));return [];}
function pointerIndex(units){const n=Math.max(units.length,1), slice=Math.PI*2/n;return Math.floor((((0-angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2))/slice);}
function pegTick(speed=1){const pointer=$("wheelPointer"); pointer.classList.remove("tick"); void pointer.offsetWidth; pointer.classList.add("tick"); beep(620+Math.min(520,speed*115),Math.max(.012,.03-Math.min(.018,speed*.004)),"square",.034);}
function syncPegTick(){const units=wheelDisplay(); if(units.length<2)return; const idx=pointerIndex(units), now=performance.now(); if(lastPegIndex<0){lastPegIndex=idx;return} if(idx!==lastPegIndex){const diff=Math.abs(idx-lastPegIndex), step=Math.min(diff,units.length-diff);lastPegIndex=idx;lastTickAt=now;pegTick(step);}}
function monthIndex(){let drawn=state.winners.length;const plan=schedule();for(let i=0;i<plan.length;i++){if(drawn<plan[i])return i;drawn-=plan[i];}return plan.length-1;}
function winnerNum(){const mi=monthIndex();return state.winners.filter(w=>w.monthIndex===mi).length+1;}
function color(i){return ["#0b5ed7","#10a05f","#ffcc33","#df2b2b","#7c3aed","#0891b2","#f97316","#16a34a","#e11d48","#2563eb"][i%10];}
function short(n){return n.length>24?n.slice(0,22)+"...":n;}
function drawWheel(highlight=-1){if(!Number.isFinite(angle))angle=0;const units=wheelDisplay(); const n=Math.max(units.length,1); const w=canvas.width,cx=w/2,cy=w/2,r=w/2-18,slice=Math.PI*2/n; ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,w,w); ctx.save(); ctx.translate(cx,cy); ctx.rotate(angle); for(let i=0;i<n;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,i*slice,(i+1)*slice);ctx.closePath();ctx.fillStyle=color(i);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.8)";ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate(i*slice+slice/2);ctx.textAlign="right";ctx.fillStyle="#fff";ctx.font=n>60?"900 19px Calibri":n>30?"900 23px Calibri":"900 28px Calibri";ctx.shadowColor="#000";ctx.shadowBlur=5;ctx.fillText(short(units[i]?.name||""),r-22,8);ctx.restore();} ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.lineWidth=12;ctx.strokeStyle="#fff";ctx.stroke();for(let i=0;i<n;i++){const a=i*slice,x=Math.cos(a)*(r-2),y=Math.sin(a)*(r-2);ctx.beginPath();ctx.arc(x,y,n>60?5:7,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#050505";ctx.stroke();}ctx.restore();}
function spinLoop(now=performance.now()){if(!spinLastTime)spinLastTime=now;const dt=Math.min(40,now-spinLastTime)/16.67;spinLastTime=now;angle+=velocity*dt;drawWheel();syncPegTick();raf=requestAnimationFrame(spinLoop);}
function start(){initAudio(); if(state.units.length!==settings().memberCount){notify("Please load exactly "+settings().memberCount+" names first.","Names Required");return} if(finalAutoReady()){assignFinalMonthIfReady();save();render();showSummary();return} if(spinning||remainingWheel().length===0)return; spinning=true; selected=null; selectedIndex=-1; displayUnits=null; displayHighlight=-1; lastPegIndex=-1; lastTickAt=0; spinLastTime=0; velocity=.92+Math.random()*.18; $("status").textContent="SPINNING"; $("start").disabled=true;$("latest").textContent="---";$("ticker").textContent="SPINNING..."; startSpinSound(); tickerTimer=setInterval(()=>{$("ticker").textContent=["SPINNING FAST...","GOOD LUCK...","DRAW IN PROGRESS..."][rand(3)];},260); spinLoop(); autoStopTimer=setTimeout(stop,1600);}
function stop(){if(!spinning)return; clearInterval(tickerTimer); slowTickSound(); $("ticker").textContent="SLOWING DOWN..."; const rem=remainingWheel(); selectedIndex=rand(rem.length); selected=rem[selectedIndex]; displayUnits=rem; displayHighlight=selectedIndex; cancelAnimationFrame(raf); const full=Math.PI*2, slice=full/rem.length, pointer=0, selectedCenter=selectedIndex*slice+slice/2; const targetBase=pointer-selectedCenter, current=angle, currentMod=((current%full)+full)%full, targetMod=((targetBase%full)+full)%full; const extraTurns=14+rand(4), delta=((targetMod-currentMod+full)%full)+(full*extraTurns), final=current+delta; const startTime=performance.now(), duration=7800+rand(1400); lastPegIndex=pointerIndex(rem); let lastAngle=current; function ease(t){return 1-Math.pow(1-t,3.2)} function settle(t){return 1+Math.sin(t*Math.PI)*.0025*(1-t)} function slow(now){const t=Math.min(1,(now-startTime)/duration), eased=settle(t)*ease(t); angle=t<1?current+delta*eased:final; const speed=Math.abs(angle-lastAngle); lastAngle=angle; drawWheel(selectedIndex); syncPegTick(); if(speed>.16)$("ticker").textContent="SLOWING DOWN..."; if(t>.52&&t<.82)$("ticker").textContent="ALMOST THERE..."; if(t>=.82&&t<1)$("ticker").textContent="FINAL MOMENTS..."; if(t<1)requestAnimationFrame(slow);else finish();} requestAnimationFrame(slow);}
function finish(){clearTimeout(revealTimer); $("ticker").textContent="Wheel stopped. Winner will be announced in 1 second..."; $("status").textContent="RESULT LOCKED"; drawWheel(selectedIndex); revealTimer=setTimeout(revealWinner,WINNER_REVEAL_DELAY_MS);}
function revealWinner(){revealTimer=null; spinning=false; const m=months()[monthIndex()], wn=winnerNum(); const rec={id:selected.id,name:selected.name,month:m,monthIndex:monthIndex(),winnerNo:wn,time:new Date().toLocaleString()}; state.winners.push(rec);audit("winner-drawn",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo,remainingAfterDraw:remainingWheel().length}); const finalAssigned=assignFinalMonthIfReady(); save(); $("ticker").textContent=finalAssigned?"Final month assigned automatically":selected.name; $("latest").textContent=selected.name; $("status").textContent="WINNER REVEALED"; fanfare(); showPopup(rec); render();}
function next(){displayUnits=null;displayHighlight=-1;$("ticker").textContent="Click BISMILLAAH to spin the wheel";$("latest").textContent="---";$("start").disabled=drawComplete();$("status").textContent=drawComplete()?"COMPLETE":"READY";drawWheel();}
function showPopup(rec){$("popMonth").textContent=rec.month+" Member #"+rec.winnerNo;animateWinnerName(rec.name);$("overlay").classList.add("show");confetti();}
function animateWinnerName(name){const el=$("popName");el.textContent="";el.setAttribute("aria-label",name);Array.from(name).forEach((ch,i)=>{const span=document.createElement("span"), spread=window.innerWidth<700?170:310, x=(Math.random()-.5)*spread, y=(Math.random()-.5)*220, rot=(Math.random()-.5)*260;span.className=ch===" "?"winnerLetter winnerSpace":"winnerLetter";span.textContent=ch===" "?"\u00a0":ch;span.style.setProperty("--from-x",x+"px");span.style.setProperty("--from-y",y+"px");span.style.setProperty("--from-r",rot+"deg");span.style.animationDelay=140+i*58+"ms";el.appendChild(span);});}
function confetti(){const box=$("confetti");box.innerHTML="";for(let i=0;i<160;i++){const p=document.createElement("i");p.style.left=Math.random()*100+"vw";p.style.background=color(i);p.style.animationDelay=Math.random()*0.4+"s";p.style.animationDuration=2+Math.random()*2+"s";box.appendChild(p);setTimeout(()=>p.remove(),4500);}}
function render(){const s=settings(), rem=remainingWheel(), ms=months(), plan=schedule(), mi=drawComplete()?plan.length-1:monthIndex(), wn=winnerNum(), maxW=maxWinnersPerMonth(), remainingCount=s.drawMode==="specific"?Math.max(0,targetWinnerCount()-state.winners.length):rem.length; $("wheelPanel").classList.toggle("drawComplete",drawComplete());$("total").textContent=state.units.length;$("remaining").textContent=remainingCount;$("drawn").textContent=state.winners.length;$("month").textContent=drawComplete()?"Completed":finalAutoReady()?ms[plan.length-1]:ms[mi];$("winnerNo").textContent=drawComplete()?s.drawMode==="specific"?"Month draw complete":"All members drawn":finalAutoReady()?"Final month will be assigned automatically":"Current Draw: "+ms[mi]+" - Member "+wn+" of "+plan[mi];$("round").textContent=drawComplete()?"Complete":finalAutoReady()?"Final month auto assignment":"Month "+(mi+1)+" / "+settings().monthCount;$("start").disabled=drawComplete()||spinning||finalAutoReady();$("undo").disabled=spinning||state.winners.length===0;$("summary").disabled=!drawComplete();$("shareAll").disabled=!drawComplete();drawWheel(displayHighlight);renderHeader($("historyHead"),maxW);renderRows($("history"),summaryRows(),maxW);}
function exportCSV(){const rows=summaryRows(), maxW=maxWinnersPerMonth(), lines=[];lines.push(["#","Month",...Array.from({length:maxW},(_,i)=>"Member "+(i+1))].map(csvCell).join(","));rows.forEach((r,i)=>lines.push([i+1,r.month,...r.names].map(csvCell).join(",")));lines.push("");lines.push(["Audit #","Action","Time","Detail"].map(csvCell).join(","));state.audit.forEach(a=>lines.push([a.no,a.action,a.time,JSON.stringify(a.detail||{})].map(csvCell).join(","))); const blob=new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="family-bc-wheel-draw-results.csv";a.click();URL.revokeObjectURL(url);}
function backupState(){audit("backup-created",{winners:state.winners.length,members:state.units.length});save();const blob=new Blob([JSON.stringify({version:6,savedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="family-bc-draw-backup.json";a.click();URL.revokeObjectURL(url);}
function restoreState(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result), restored=data.state||data; if(!Array.isArray(restored.units)||!Array.isArray(restored.wheelOrder)||!Array.isArray(restored.winners))throw new Error("Invalid backup"); state=restored;normalizeState();audit("backup-restored",{fileName:file.name||"backup",winners:state.winners.length,members:state.units.length});save();displayUnits=null;displayHighlight=-1;$("startMonth").value=settings().startMonth;$("memberCount").value=settings().memberCount;$("monthCount").value=settings().monthCount;$("drawPerMonth").value=settings().drawPerMonth;$("names").value=state.units.join("\n");updateRunnerChoices(settings().runnerNames);render();notify("Backup restored successfully.","Backup Restored");}catch(e){notify("Could not restore this backup file.","Restore Failed");}};reader.readAsText(file);}
function summaryRows(){const ms=months(), maxW=maxWinnersPerMonth();return ms.map((m,i)=>{const monthWinners=state.winners.filter(x=>x.monthIndex===i);return {month:m,names:Array.from({length:maxW},(_,j)=>monthWinners.find(x=>x.winnerNo===j+1)?.name||"")};});}
function showSummary(){const rows=summaryRows(), maxW=maxWinnersPerMonth();$("summaryIntro").textContent=drawComplete()?"All draws are complete.":"Draw is not complete yet.";renderResultsTable($("summaryList"),rows,maxW);$("summaryOverlay").classList.add("show");}
function shareCaption(){const s=settings(), rows=summaryRows();let msg=document.title+"\n\n"+(s.drawMode==="specific"?"Month Draw Results":"Final Draw Results")+"\n";rows.forEach((r,i)=>{msg+=`${i+1}. ${r.month}: ${r.names.filter(Boolean).join(", ")}\n`;});return msg.trim();}
function wrapCanvasText(ctx,text,x,y,maxWidth,lineHeight,maxLines=4){const words=String(text||"").split(/\s+/).filter(Boolean), lines=[];let line="";words.forEach(word=>{const next=line?line+" "+word:word;if(ctx.measureText(next).width<=maxWidth)line=next;else{if(line)lines.push(line);line=word;}});if(line)lines.push(line);const out=lines.slice(0,maxLines);if(lines.length>maxLines)out[out.length-1]=out[out.length-1].replace(/\s+\S*$/,"")+"...";out.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return out.length*lineHeight;}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function canvasBlob(canvas){return new Promise(resolve=>canvas.toBlob(resolve,"image/png",0.96));}
function buildShareImage(){const rows=summaryRows(), s=settings(), width=1080, margin=56, monthW=250, rowGap=10, baseRow=72, ctx=document.createElement("canvas").getContext("2d");ctx.canvas.width=width;ctx.font="800 30px Calibri, Arial";const measured=rows.map(r=>{const names=r.names.filter(Boolean).map((n,i)=>`${i+1}. ${n}`).join("   ")||"---";const nameLines=Math.max(1,Math.ceil(ctx.measureText(names).width/(width-margin*2-monthW-32)));return {row:r,names,height:Math.max(baseRow,44+Math.min(4,nameLines)*28)};});const height=Math.max(900,300+measured.reduce((sum,r)=>sum+r.height+rowGap,0));const canvas=ctx.canvas;canvas.height=height;const g=ctx.createLinearGradient(0,0,width,height);g.addColorStop(0,"#073b8e");g.addColorStop(.55,"#0a84ff");g.addColorStop(1,"#067647");ctx.fillStyle=g;ctx.fillRect(0,0,width,height);ctx.fillStyle="rgba(255,255,255,.10)";for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(width-120-i*115,95+i*32,90+i*7,0,Math.PI*2);ctx.fill();}roundRect(ctx,36,36,width-72,height-72,34);ctx.fillStyle="#fffffff2";ctx.fill();ctx.fillStyle="#073b8e";ctx.font="1000 46px Calibri, Arial";ctx.fillText(s.drawMode==="specific"?"Seettu Kulukkal Month Draw":"Seettu Kulukkal Final Draw",margin,105);ctx.fillStyle="#067647";ctx.font="900 30px Calibri, Arial";ctx.fillText(s.drawMode==="specific"?rows[0]?.month||months()[0]:`${months()[0]} to ${months()[months().length-1]}`,margin,148);ctx.fillStyle="#667085";ctx.font="800 23px Calibri, Arial";ctx.fillText(`Generated ${new Date().toLocaleString()}  •  ${state.units.length} eligible members`,margin,184);ctx.fillStyle="#101828";roundRect(ctx,margin,218,width-margin*2,54,16);ctx.fillStyle="#eef4fb";ctx.fill();ctx.fillStyle="#0a3a82";ctx.font="1000 24px Calibri, Arial";ctx.fillText("Month",margin+18,252);ctx.fillText("Winners",margin+monthW+26,252);let y=286;measured.forEach((item,i)=>{roundRect(ctx,margin,y,width-margin*2,item.height,16);ctx.fillStyle=i%2?"#f7f9fc":"#ffffff";ctx.fill();ctx.fillStyle="#0a3a82";ctx.font="1000 24px Calibri, Arial";wrapCanvasText(ctx,item.row.month,margin+18,y+38,monthW-26,26,2);ctx.fillStyle="#101828";ctx.font="900 25px Calibri, Arial";wrapCanvasText(ctx,item.names,margin+monthW+26,y+38,width-margin*2-monthW-44,28,4);y+=item.height+rowGap;});ctx.fillStyle="#8a6200";ctx.font="900 22px Calibri, Arial";ctx.fillText("Charity does not decrease wealth.  •  Sahih Muslim 2588",margin,height-68);return canvas;}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob), a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);}
function isComputerBrowser(){return !(navigator.userAgentData?.mobile||/Android|iPhone|iPad|iPod|IEMobile|Opera Mini/i.test(navigator.userAgent));}
function openWhatsAppWeb(caption){const opened=window.open("https://web.whatsapp.com/send?text="+encodeURIComponent(caption),"_blank","noopener");if(!opened)notify("Please allow popups for this page, then try opening WhatsApp Web again.","Popup Blocked");}
function asciiBytes(text){return new TextEncoder().encode(text);}
function base64Bytes(base64){const bin=atob(base64), bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes;}
function imagePdf(canvas){const data=canvas.toDataURL("image/jpeg",.92).split(",")[1], image=base64Bytes(data), pageW=612, pageH=Math.max(792,Math.round(pageW*canvas.height/canvas.width)), content=`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im0 Do\nQ\n`, parts=[], offsets=[];let offset=0;const push=part=>{if(typeof part==="string")part=asciiBytes(part);parts.push(part);offset+=part.length;}, obj=(n,body)=>{offsets[n]=offset;push(`${n} 0 obj\n${body}\nendobj\n`);};push("%PDF-1.4\n");obj(1,"<< /Type /Catalog /Pages 2 0 R >>");obj(2,"<< /Type /Pages /Kids [3 0 R] /Count 1 >>");obj(3,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);offsets[4]=offset;push(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`);push(image);push("\nendstream\nendobj\n");obj(5,`<< /Length ${content.length} >>\nstream\n${content}endstream`);const xref=offset;push(`xref\n0 6\n0000000000 65535 f \n${[1,2,3,4,5].map(i=>`${String(offsets[i]).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(parts,{type:"application/pdf"});}
async function downloadResultImage(){if(!drawComplete()){notify("Download Image is available after the draw is complete.","Draw Not Complete");return}const blob=await canvasBlob(buildShareImage());if(!blob){notify("Could not create the result image.","Download Failed");return}downloadBlob(blob,"seettu-kulukkal-draw-results.png");notify("The final result image has been downloaded.","Image Downloaded");}
function downloadResultPdf(){if(!drawComplete()){notify("Download PDF is available after the draw is complete.","Draw Not Complete");return}downloadBlob(imagePdf(buildShareImage()),"seettu-kulukkal-draw-results.pdf");notify("The final result PDF has been downloaded.","PDF Downloaded");}
async function shareAllResults(){if(!drawComplete()){notify("Share Image is available after the draw is complete.","Draw Not Complete");return} const canvas=buildShareImage(), blob=await canvasBlob(canvas), fileName="seettu-kulukkal-draw-results.png", caption=shareCaption();if(!blob){notify("Could not create the share image.","Share Failed");return}const file=new File([blob],fileName,{type:"image/png"});if(!isComputerBrowser()&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:"Seettu Kulukkal Draw Results",text:caption});return}catch(e){if(e.name==="AbortError")return;}}downloadBlob(blob,fileName);if(isComputerBrowser()){showDialog({title:"Image Ready for WhatsApp",message:"The final result image has been downloaded.\n\nClick Open WhatsApp Web, choose the group or member, then attach the downloaded image from your Downloads folder.",okText:"Open WhatsApp Web",cancelText:"Done",onYes:()=>openWhatsAppWeb(caption)});return}notify("The result image has been downloaded.\n\nAttach it in WhatsApp to share with members.","Image Ready");}
function undoLast(){if(spinning||!state.winners.length)return;const autoText="Assigned automatically as final month remaining member";let autoCount=0;while(state.winners.length&&state.winners[state.winners.length-1].time===autoText){state.winners.pop();autoCount++;}const last=state.winners[state.winners.length-1];if(!last){save();render();return}const extra=autoCount?"\n\nThis will also remove "+autoCount+" automatic final month member(s).":"";ask("Undo last member: "+last.name+"?"+extra,()=>{const undone=state.winners.pop();audit("winner-undone",{id:undone.id,name:undone.name,month:undone.month,winnerNo:undone.winnerNo,autoFinalRemoved:autoCount});displayUnits=null;displayHighlight=-1;save();$("latest").textContent="---";$("ticker").textContent="Click BISMILLAAH to spin the wheel";$("status").textContent="READY";render();},()=>{assignFinalMonthIfReady();save();render();},"Undo Last Draw");}
function setPresentation(on){document.querySelector(".app").classList.toggle("presentation",on);if(on)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.().catch(()=>{});}
let wizardStep=0;
function wizardNames(){return $("wizNames").value.split(/\n/).map(x=>x.trim()).filter(Boolean);}
function wizardMode(){return document.querySelector("input[name='wizDrawMode']:checked")?.value==="specific"?"specific":"full";}
function wizardSettings(){const mode=wizardMode(), monthCount=Math.max(1,Number($("wizMonthCount").value)||0), drawPerMonth=Math.max(1,Number($("wizDrawPerMonth").value)||0), targetDrawCount=Math.max(1,Number($("wizSpecificCount").value)||drawPerMonth), startMonth=mode==="specific"?$("wizSpecificMonth").value||$("wizStartMonth").value||settings().startMonth:$("wizStartMonth").value||settings().startMonth;return {drawMode:mode,startMonth,monthCount:mode==="specific"?1:monthCount,drawPerMonth:mode==="specific"?targetDrawCount:drawPerMonth,targetDrawCount,memberCount:Math.max(1,Number($("wizMemberCount").value)||(mode==="specific"?wizardNames().length:monthCount*drawPerMonth))};}
function wizardRunnerNames(){return Array.from(document.querySelectorAll("#wizRunners input:checked")).map(x=>x.value);}
function setWizardError(message=""){$("wizardError").textContent=message;}
function updateWizardModeFields(){const specific=wizardMode()==="specific";document.querySelectorAll(".wizardSpecificField").forEach(el=>el.style.display=specific?"flex":"none");$("wizStartMonth").closest("label").style.display=specific?"none":"flex";$("wizMonthCount").closest("label").style.display=specific?"none":"flex";$("wizDrawPerMonth").closest("label").style.display=specific?"none":"flex";}
function updateWizardCounts(){updateWizardModeFields();const s=wizardSettings(), expected=s.monthCount*s.drawPerMonth, count=wizardNames().length;if(s.drawMode==="specific"){$("wizExpected").textContent=`Specific month draw: choose ${s.targetDrawCount} winner${s.targetDrawCount===1?"":"s"} from the member pool.`;$("wizNameCount").textContent=`${count} eligible member${count===1?"":"s"} entered. Need at least ${s.targetDrawCount}.`;}else{$("wizExpected").textContent=`Expected members: ${s.monthCount} months x ${s.drawPerMonth} draw/month = ${expected}.`;$("wizMemberCount").value=Number($("wizMemberCount").value)||expected;$("wizNameCount").textContent=`${count} member${count===1?"":"s"} entered. Expected ${s.memberCount}.`;}}
function updateWizardRunnerChoices(){const box=$("wizRunners"), names=wizardNames(), selected=wizardRunnerNames(), counts=new Map();box.textContent="";names.forEach(name=>{const key=name.toLowerCase(), count=(counts.get(key)||0)+1;counts.set(key,count);const row=document.createElement("label"), check=document.createElement("input"), text=document.createElement("span");row.className="runnerOption";check.type="checkbox";check.value=name;check.checked=selected.some(x=>x.toLowerCase()===key);check.addEventListener("change",()=>{const limit=wizardSettings().drawPerMonth, checked=Array.from(document.querySelectorAll("#wizRunners input:checked"));if(checked.length>limit){check.checked=false;setWizardError(`Choose up to ${limit} draw runner${limit===1?"":"s"}.`);}else setWizardError("");});text.textContent=count>1?`${name} (${count})`:name;row.append(check,text);box.appendChild(row);});}
function renderWizardReview(){const s=wizardSettings(), names=wizardNames(), runners=wizardRunnerNames(), expected=s.monthCount*s.drawPerMonth, start=new Date(`${s.startMonth}-01T00:00:00`), end=new Date(start.getFullYear(),start.getMonth()+s.monthCount-1,1), endLabel=monthLabel(end), items=s.drawMode==="specific"?[["Mode","Specific month only"],["Draw month",monthLabel(start)],["Winners needed",String(s.targetDrawCount)],["Eligible members",String(names.length)],["Draw runners",runners.length?runners.join(", "):"None selected"]]:[["Mode","Full schedule"],["Start month",monthValueLabel(s.startMonth)],["End month",endLabel],["Months",String(s.monthCount)],["Draw per month",String(s.drawPerMonth)],["Expected members",String(expected)],["Members entered",String(names.length)],["Draw runners",runners.length?runners.join(", "):"None selected"]], wrap=document.createElement("dl");$("wizReview").textContent="";items.forEach(([k,v])=>{const dt=document.createElement("dt"), dd=document.createElement("dd");dt.textContent=k;dd.textContent=v;wrap.append(dt,dd);});$("wizReview").appendChild(wrap);}
function validateWizardStep(step=wizardStep){const s=wizardSettings(), names=wizardNames(), expected=s.monthCount*s.drawPerMonth;if(step===0){if(!/^\d{4}-\d{2}$/.test(s.startMonth))return "Choose a valid draw month.";if(s.drawMode==="full"&&s.memberCount!==expected)return `Total Members must be ${expected} for this setup.`;if(s.drawMode==="specific"&&s.targetDrawCount>s.memberCount)return "Winners needed cannot be more than total eligible members.";}if(step===1){if(s.drawMode==="full"&&names.length!==s.memberCount)return `Enter exactly ${s.memberCount} member names. Current count is ${names.length}.`;if(s.drawMode==="specific"&&names.length<s.targetDrawCount)return `Enter at least ${s.targetDrawCount} eligible member names. Current count is ${names.length}.`;}if(step===2){const runners=wizardRunnerNames();if(runners.length>s.drawPerMonth)return `Choose up to ${s.drawPerMonth} draw runner${s.drawPerMonth===1?"":"s"}.`;}return "";}
function renderWizard(){setWizardError("");document.querySelectorAll(".wizardStep").forEach(step=>step.classList.toggle("active",Number(step.dataset.step)===wizardStep));$("wizardStepLabel").textContent=`Step ${wizardStep+1} of 4`;$("wizardProgress").style.width=`${(wizardStep+1)*25}%`;$("wizardBack").disabled=wizardStep===0;$("wizardNext").textContent=wizardStep===3?"Apply Setup":"Next";updateWizardCounts();if(wizardStep===2)updateWizardRunnerChoices();if(wizardStep===3)renderWizardReview();}
function openWizard(){if(document.querySelector(".app").classList.contains("setupLocked")){notify("Unlock setup before using the setup wizard.","Setup Locked");return}const s=settings();$("wizModeFull").checked=s.drawMode!=="specific";$("wizModeSpecific").checked=s.drawMode==="specific";$("wizStartMonth").value=$("startMonth").value||s.startMonth;$("wizSpecificMonth").value=s.startMonth;$("wizMonthCount").value=s.drawMode==="specific"?20:$("monthCount").value||s.monthCount;$("wizDrawPerMonth").value=$("drawPerMonth").value||s.drawPerMonth;$("wizSpecificCount").value=s.targetDrawCount||s.drawPerMonth;$("wizMemberCount").value=$("memberCount").value||s.memberCount;$("wizNames").value=$("names").value;wizardStep=0;$("wizardOverlay").classList.add("show");$("wizardOverlay").setAttribute("aria-hidden","false");renderWizard();(s.drawMode==="specific"?$("wizSpecificMonth"):$("wizStartMonth")).focus();}
function closeWizard(){$("wizardOverlay").classList.remove("show");$("wizardOverlay").setAttribute("aria-hidden","true");setWizardError("");}
function applyWizard(){const error=validateWizardStep(3);if(error){setWizardError(error);return}const s=wizardSettings(), names=wizardNames(), runners=wizardRunnerNames();$("startMonth").value=s.startMonth;$("monthCount").value=s.monthCount;$("drawPerMonth").value=s.drawPerMonth;$("memberCount").value=names.length;$("names").value=names.join("\n");pendingSetupMode={drawMode:s.drawMode,targetDrawCount:s.targetDrawCount};updateRunnerChoices(runners);document.querySelectorAll("#drawRunners input").forEach(check=>{check.checked=runners.some(x=>x.toLowerCase()===check.value.toLowerCase());});closeWizard();$("load").click();}
$("setupWizard").onclick=openWizard;$("wizardClose").onclick=closeWizard;$("wizardBack").onclick=()=>{if(wizardStep>0){wizardStep--;renderWizard();}};$("wizardNext").onclick=()=>{const error=validateWizardStep();if(error){setWizardError(error);return}if(wizardStep<3){wizardStep++;renderWizard();}else applyWizard();};
["wizMonthCount","wizDrawPerMonth"].forEach(id=>$(id).addEventListener("input",()=>{if(wizardMode()==="full"){const s=wizardSettings();$("wizMemberCount").value=s.monthCount*s.drawPerMonth;}updateWizardCounts();if(wizardStep===3)renderWizardReview();}));
["wizModeFull","wizModeSpecific"].forEach(id=>$(id).addEventListener("change",()=>{updateWizardCounts();if(wizardStep===3)renderWizardReview();}));
["wizStartMonth","wizSpecificMonth","wizSpecificCount","wizMemberCount"].forEach(id=>$(id).addEventListener("input",()=>{updateWizardCounts();if(wizardStep===3)renderWizardReview();}));
$("wizNames").addEventListener("input",()=>{updateWizardCounts();if(wizardStep===2)updateWizardRunnerChoices();if(wizardStep===3)renderWizardReview();});
$("load").onclick=()=>{const units=parse(), runnerNames=parseRunners(), startMonth=$("startMonth").value||"2026-07", memberCount=Math.max(1,Number($("memberCount").value)||0), rawMonthCount=Math.max(1,Number($("monthCount").value)||0), rawDrawPerMonth=Math.max(1,Number($("drawPerMonth").value)||0), mode=pendingSetupMode||{drawMode:"full",targetDrawCount:rawDrawPerMonth}, drawMode=mode.drawMode==="specific"?"specific":"full", targetDrawCount=Math.max(1,Number(mode.targetDrawCount)||rawDrawPerMonth), monthCount=drawMode==="specific"?1:rawMonthCount, drawPerMonth=drawMode==="specific"?targetDrawCount:rawDrawPerMonth, expected=monthCount*drawPerMonth; if(drawMode==="full"&&memberCount!==expected){pendingSetupMode=null;notify("Total Members must be Total Months x Total Draw Per Month.\n\n"+monthCount+" months x "+drawPerMonth+" draw per month needs "+expected+" members.","Setup Mismatch");return} if(units.length!==memberCount){pendingSetupMode=null;notify("You entered "+units.length+" names.\n\nPlease enter exactly "+memberCount+" names, or update Total Members.","Member Count Mismatch");return} if(drawMode==="specific"&&units.length<targetDrawCount){pendingSetupMode=null;notify("Specific month draw needs at least "+targetDrawCount+" eligible member names.","Member Count Mismatch");return} if(runnerNames.length>drawPerMonth){pendingSetupMode=null;notify("Draw Runners cannot be more than Draw / Month.\n\nPlease enter up to "+drawPerMonth+" runner name(s).","Too Many Draw Runners");return} const previousSettings=state.settings; state.settings={memberCount,monthCount,drawPerMonth,startMonth,runnerNames,drawMode,targetDrawCount}; const assigned=runnerRecords(units,runnerNames); const missing=runnerNames.filter((_,i)=>!assigned[i]); if(missing.length){state.settings=previousSettings;pendingSetupMode=null;notify("Draw Runner name(s) not found in member list:\n\n"+missing.join(", "),"Draw Runner Not Found");return} displayUnits=null;displayHighlight=-1;state.units=units; state.wheelOrder=secureShuffle(units.map((name,i)=>({id:i,name}))); state.winners=assigned.filter(Boolean); state.audit=[]; audit("setup-loaded",{members:memberCount,months:monthCount,drawPerMonth,startMonth,drawRunners:runnerNames.length,drawMode,targetDrawCount}); state.winners.forEach(rec=>audit("runner-preassigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo})); assignFinalMonthIfReady(); pendingSetupMode=null; save(); render(); const modeText=drawMode==="specific"?"Specific month draw loaded for "+months()[0]+".":"Names loaded from "+months()[0]+" across "+monthCount+" months."; notify(memberCount+" names loaded.\n\n"+modeText+"\n\n"+state.winners.length+" member(s) assigned automatically for fixed first/last month rules.","Names Loaded");};
$("reset").onclick=()=>{ask("Reset all draw results?\n\nDraw runners and final month rules will stay assigned automatically.",()=>{displayUnits=null;displayHighlight=-1;state.audit=[];audit("draw-reset",{members:state.units.length});state.winners=runnerRecords(state.units,settings().runnerNames).filter(Boolean);state.winners.forEach(rec=>audit("runner-preassigned",{id:rec.id,name:rec.name,month:rec.month,winnerNo:rec.winnerNo}));assignFinalMonthIfReady();save();next();render();},null,"Reset Draw");};
$("start").onclick=start;$("setupToggle").onclick=()=>setSetupHidden(true);$("setupShow").onclick=()=>setSetupHidden(false);$("lockSetup").onclick=()=>setSetupLocked(!document.querySelector(".app").classList.contains("setupLocked"));$("continue").onclick=()=>{$("overlay").classList.remove("show");if(drawComplete())showSummary();};$("export").onclick=exportCSV;$("print").onclick=()=>window.print();
$("undo").onclick=undoLast;$("backup").onclick=backupState;$("restore").onclick=()=>$("restoreFile").click();$("restoreFile").onchange=e=>{if(e.target.files[0])restoreState(e.target.files[0]);e.target.value="";};$("presentation").onclick=()=>setPresentation(true);$("exitPresentation").onclick=()=>setPresentation(false);$("summary").onclick=showSummary;$("summaryClose").onclick=()=>$("summaryOverlay").classList.remove("show");$("shareAll").onclick=shareAllResults;$("summaryShare").onclick=shareAllResults;$("summaryImage").onclick=downloadResultImage;$("summaryPdf").onclick=downloadResultPdf;$("summaryCsv").onclick=exportCSV;
$("names").addEventListener("input",()=>updateRunnerChoices());
$("drawPerMonth").addEventListener("input",()=>enforceRunnerLimit());
loadState();setSetupHidden(autoOpenSetupWizard?false:localStorage.getItem(STORAGE+"_setup_hidden")==="1");setSetupLocked(autoOpenSetupWizard?false:localStorage.getItem(STORAGE+"_setup_locked")==="1");if(autoOpenSetupWizard)setTimeout(openWizard,80);setTimeout(()=>drawWheel(displayHighlight),650);
